### ISSUE TITLE
Disable SSL verification

### ISSUE THREAD

**Issue by CaseyBurnsSv** [artilleryio/minigun#8]
Hello. Loving this tool.

How can I configure it to not validate SSL certs. I am using self-signed certs in our staging environment.

All requests are errors - DEPTH_ZERO_SELF_SIGNED_CERT.

Thank you!

**Comment by hassy** [comment]
Hi @CaseyBurnsSv, glad to hear that! We have in fact just implemented this in minigun-core - https://github.com/artilleryio/minigun-core/issues/5. I'll push a new release to npm later today.

**Comment by hassy** [comment]
@CaseyBurnsSv I just published Minigun 0.0.15 which now has the `--k` (or `--insecure` - just like `curl`) option to disable validation. Alternatively, validation can be disabled in the test script with:

```javascript
{
  "config": {
    "target": "https://myapp.staging:3002",
    "tls": {
      "rejectUnauthorized": false
    }
    // ... 
  },
  "scenarios": [
    // ... 
  ]
}
```

Give it a go and let me know what you think.

And speaking of environments - if you have any thoughts on environment support, please share them here: https://github.com/artilleryio/minigun/issues/2. :)

**Comment by CaseyBurnsSv** [comment]
Hi. Working perfectly! Thank you for the fast update.

`--insecure` and `"rejectUnauthorized": false` work. `--k` gave me `error: unknown option `--k`.

**Comment by leelak98** [comment]
Guys thank you very much made my day --insecure works well

**Comment by JimLynchCodes** [comment]
hmm,  I tried both the flag and tls in the config, but I'm still getting this error for all requests... 🤔

```
  Errors:
    SELF_SIGNED_CERT_IN_CHAIN: 1
```

**Comment by bluezombie** [comment]
> hmm, I tried both the flag and tls in the config, but I'm still getting this error for all requests... 🤔
> 
> ```
>   Errors:
>     SELF_SIGNED_CERT_IN_CHAIN: 1
> ```

Got the same a few minutes ago... is this being solved on this last version?

`gotero@XXXXXXXXX:~/projects/oracle_performance_test$ node -v
v16.0.0
gotero@XXXXXXXXX:~/projects/oracle_performance_test$ npm -v
7.10.0
gotero@XXXXXXXXX:~/projects/oracle_performance_test$ cat test.yml | grep -B1 reject
  tls:
    - rejectUnauthorized: false
`

**Comment by hassy** [comment]
@JimLynchCodes & @bluezombie thank you for letting us know - I created a new issue here: #1006

**Comment by nobitran** [comment]
https://www.artillery.io/docs/guides/guides/command-line#turn-off-tls-verification

**Comment by bluezombie** [comment]
Thanks @hassy. I'll be testing this out.
